### ISSUE TITLE
move feature

### ISSUE THREAD

**Issue by FevLoad** [mrtambour/easy-zip-to-cbz#2]
Thank you very much for this script 
and I really grateful for your amazing work

So, I want to ask if it's possible to add the ability for the script to be able to move each *.cbz to its own folder with the file name 
I've like +3000 file inside a parent folder and I'm looking for a way to move them to sub-folders contain each file's name as a folder name.

**Comment by mrtambour** [comment]
I don't know if you still need that function, but I added it in the dev branch and released a new beta build for anyone interested. 
https://github.com/mrtambour/easy-zip-to-cbz/releases/tag/0.5.0

I did some testing and it worked fine although I don't have thousands of files to convert at the moment. All you need to do is create a config.txt and set **folder-for-each-archive = true** and run the executable. 
I recommend you leave **leave-original-file = true** to be safe and do some tests beforehand. Both lines must be included in config.

leave-original-file = true
folder-for-each-archive = true

**Comment by FevLoad** [comment]
Firstly Sorry for not replying sooner 
I aplogize for that matter.

I tested the new script 
and it does create folders for each file in the parent folder 
but it didn't convert them nor move them to the new path for each file.

**Comment by mrtambour** [comment]
Don't worry its ok. I found the problem and fixed it in this commit 4e4019975b7071e652f8f37ea57a2cdb933a6be3

**Comment by FevLoad** [comment]
Thanks for understanding, it's appreciated 

for the commit would you please show me how to apply the fix  and test it on my device?
do I need to compile the script ?
---> has Zero knowledge about coding or programming.

**Comment by mrtambour** [comment]
I'm gonna try to release a new version tomorrow fully built including all the changes i've made recently

**Comment by mrtambour** [comment]
After looking at stuff I still need to finish still I decided to release a quick 0.5.1 build right now instead
[v0.5.1-beta](https://github.com/mrtambour/easy-zip-to-cbz/releases/tag/0.5.1-beta)
@FevLoad 

I was only able to do some quick checks before uploading this quick release. If anyone encounters any new problems please post here or make a new issue

**Comment by FevLoad** [comment]
Thanks, I'm testing now.
And it's working perfectly. 
Thanks mate, Thank you so much!!

**Comment by mrtambour** [comment]
I'm glad its working, if you notice any other bugs open a new issue and i'll take a look.

**Comment by FevLoad** [comment]
Hello there @mrtambour Sorry for re-opening this enhancement issue again 
would it be possible to make it able to move already "cbz" ext file to folder without convert the ext  from "zip" to "cbz" 
like for an example I've this file 
```
WITCH WATCH 109 (2023) (Digital) (anadius).cbz
``` 
is it possible to add moving feature for already "cbz" ext file to a folder 
like WITCH WATCH 109 (2023) (Digital) (anadius).cbz
script should recognize the pattern and move the files to folder with the same file name 
known that the folder name should be copy up till before "numbers"
so WITCH WATCH 109 (2023) (Digital) (anadius).cbz is the file name 
folder name should be ` WITCH WATCH`

I don't know if this can be done but it will be great for people who collect the digital copy of daily release Mangas
